"""initial_schema

Revision ID: 4b57eb0ca79e
Revises: 
Create Date: 2026-07-24 13:30:55.576806-05:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b57eb0ca79e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario'), ['usuario'], unique=False)
        batch_op.create_index('ix_auditoria_usuario_fecha', ['usuario', 'fecha'], unique=False)

    op.create_table('autos',
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cilindraje', sa.String(length=30), nullable=True),
    sa.Column('transmision', sa.String(length=30), nullable=True),
    sa.Column('combustible', sa.String(length=30), nullable=True),
    sa.Column('no_motor', sa.String(length=80), nullable=True),
    sa.Column('no_chasis', sa.String(length=80), nullable=True),
    sa.Column('propietario', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='Disponible', nullable=False),
    sa.Column('costo_fijo_mensual', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('kilometraje', sa.Float(), server_default='0.00', nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('tipo_adquisicion', sa.String(length=30), nullable=True),
    sa.Column('proximo_aceite', sa.Integer(), server_default='0', nullable=True),
    sa.Column('proximo_frenos', sa.Integer(), server_default='0', nullable=True),
    sa.Column('vencimiento_soat', sa.Date(), nullable=True),
    sa.Column('vencimiento_tecnico', sa.Date(), nullable=True),
    sa.Column('vencimiento_extintor', sa.Date(), nullable=True),
    sa.Column('vencimiento_bateria', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('placa'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autos_estado'), ['estado'], unique=False)
        batch_op.create_index('ix_autos_estado_tipo', ['estado', 'tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_autos_tipo'), ['tipo'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_doc', sa.String(length=30), nullable=True),
    sa.Column('no_doc', sa.String(length=30), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('nombre_completo', sa.String(length=200), server_default='', nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('celular2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado_region', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('nacionalidad', sa.String(length=80), nullable=True),
    sa.Column('dir_residencia', sa.String(length=200), nullable=True),
    sa.Column('dir_temporal', sa.String(length=200), nullable=True),
    sa.Column('hotel', sa.String(length=150), nullable=True),
    sa.Column('habitacion', sa.String(length=30), nullable=True),
    sa.Column('no_licencia', sa.String(length=50), nullable=True),
    sa.Column('tipo_licencia', sa.String(length=50), nullable=True),
    sa.Column('vencimiento_licencia', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='Activo', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_estado'), ['estado'], unique=False)
        batch_op.create_index('ix_clientes_estado_nombre', ['estado', 'nombre_completo'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_no_doc'), ['no_doc'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_nombre_completo'), ['nombre_completo'], unique=False)

    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('clave'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('debe_cambiar_password', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('gastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('comprobante', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=50), server_default='Sistema', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placa'], ['autos.placa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index('ix_gastos_categoria_fecha', ['categoria', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_placa'), ['placa'], unique=False)
        batch_op.create_index('ix_gastos_placa_fecha', ['placa', 'fecha'], unique=False)

    op.create_table('mantenimiento_vehiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('pieza_varias_tipo', sa.String(length=80), nullable=True),
    sa.Column('pieza_varias_fecha', sa.Date(), nullable=True),
    sa.Column('pieza_varias_desc', sa.String(length=250), nullable=True),
    sa.Column('pieza_varias_obs', sa.Text(), nullable=True),
    sa.Column('cost_varios', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('km_proximo_cambio_aceite', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_mantenimiento', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placa'], ['autos.placa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('mantenimiento_vehiculos', schema=None) as batch_op:
        batch_op.create_index('ix_mantenimiento_placa_fecha', ['placa', 'pieza_varias_fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_mantenimiento_vehiculos_placa'), ['placa'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('nacionalidad', sa.String(length=80), nullable=True),
    sa.Column('categoria_vehiculo', sa.String(length=50), nullable=True),
    sa.Column('placa_asignada', sa.String(length=20), nullable=True),
    sa.Column('fecha_recogida', sa.Date(), nullable=True),
    sa.Column('hora_recogida', sa.Time(), nullable=True),
    sa.Column('ubicacion_recogida', sa.String(length=200), nullable=True),
    sa.Column('fecha_retorno', sa.Date(), nullable=True),
    sa.Column('hora_retorno', sa.Time(), nullable=True),
    sa.Column('ubicacion_retorno', sa.String(length=200), nullable=True),
    sa.Column('dias_calculados', sa.Integer(), server_default='0', nullable=True),
    sa.Column('horas_extras', sa.Integer(), server_default='0', nullable=True),
    sa.Column('valor_dia', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('valor_hora_adic', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('abono', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='Confirmada', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['placa_asignada'], ['autos.placa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_estado'), ['estado'], unique=False)
        batch_op.create_index('ix_reservas_estado_fecha', ['estado', 'fecha_recogida'], unique=False)

    op.create_table('rentas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('no_licencia', sa.String(length=50), nullable=True),
    sa.Column('nacionalidad', sa.String(length=80), nullable=True),
    sa.Column('fecha_recogida', sa.Date(), nullable=True),
    sa.Column('hora_recogida', sa.Time(), nullable=True),
    sa.Column('ubicacion_recogida', sa.String(length=200), nullable=True),
    sa.Column('fecha_retorno', sa.Date(), nullable=True),
    sa.Column('hora_retorno', sa.Time(), nullable=True),
    sa.Column('ubicacion_retorno', sa.String(length=200), nullable=True),
    sa.Column('dias_calculados', sa.Integer(), server_default='0', nullable=True),
    sa.Column('horas_extras', sa.Integer(), server_default='0', nullable=True),
    sa.Column('valor_dia', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('valor_hora_extra', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('valor_dia_extra', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_lavado', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_silla', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_retorno', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_domicilio', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_cables', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_inversor', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('impuestos', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('abono', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('saldo_pendiente', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('estado', sa.String(length=30), server_default='Activo', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_devolucion_real', sa.Date(), nullable=True),
    sa.Column('hora_devolucion_real', sa.Time(), nullable=True),
    sa.Column('km_final', sa.String(length=20), nullable=True),
    sa.Column('tanque_final', sa.String(length=20), nullable=True),
    sa.Column('km_salida', sa.Float(), server_default='0.00', nullable=False),
    sa.Column('tanque_salida', sa.String(length=20), server_default='Lleno', nullable=True),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['placa'], ['autos.placa'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('rentas', schema=None) as batch_op:
        batch_op.create_index('idx_rentas_estado', ['estado'], unique=False)
        batch_op.create_index('idx_rentas_estado_fecha_retorno', ['estado', 'fecha_retorno'], unique=False)
        batch_op.create_index('idx_rentas_estado_placa', ['estado', 'placa'], unique=False)
        batch_op.create_index('idx_rentas_fechas', ['fecha_recogida', 'fecha_retorno'], unique=False)
        batch_op.create_index(batch_op.f('ix_rentas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_rentas_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_rentas_placa'), ['placa'], unique=False)

    op.create_table('comparendos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('fecha_infraccion', sa.Date(), nullable=False),
    sa.Column('hora_infraccion', sa.Time(), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id_renta', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='Pendiente', nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_renta'], ['rentas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['placa'], ['autos.placa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('comparendos', schema=None) as batch_op:
        batch_op.create_index('ix_comparendos_placa_fecha', ['placa', 'fecha_infraccion'], unique=False)

    op.create_table('inspecciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_renta', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('kilometraje', sa.Float(), nullable=False),
    sa.Column('nivel_gasolina', sa.String(length=20), nullable=False),
    sa.Column('limpieza', sa.String(length=50), server_default='Limpio', nullable=True),
    sa.Column('tiene_repuesto', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('tiene_gato_cruceta', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('tiene_kit_carretera', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('tiene_documentos', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('danos_carroceria', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_renta'], ['rentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_renta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=80), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_renta'], ['rentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index('ix_pagos_renta_fecha', ['id_renta', 'fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index('ix_pagos_renta_fecha')

    op.drop_table('pagos')
    op.drop_table('inspecciones')
    with op.batch_alter_table('comparendos', schema=None) as batch_op:
        batch_op.drop_index('ix_comparendos_placa_fecha')

    op.drop_table('comparendos')
    with op.batch_alter_table('rentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rentas_placa'))
        batch_op.drop_index(batch_op.f('ix_rentas_id_cliente'))
        batch_op.drop_index(batch_op.f('ix_rentas_estado'))
        batch_op.drop_index('idx_rentas_fechas')
        batch_op.drop_index('idx_rentas_estado_placa')
        batch_op.drop_index('idx_rentas_estado_fecha_retorno')
        batch_op.drop_index('idx_rentas_estado')

    op.drop_table('rentas')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index('ix_reservas_estado_fecha')
        batch_op.drop_index(batch_op.f('ix_reservas_estado'))

    op.drop_table('reservas')
    with op.batch_alter_table('mantenimiento_vehiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mantenimiento_vehiculos_placa'))
        batch_op.drop_index('ix_mantenimiento_placa_fecha')

    op.drop_table('mantenimiento_vehiculos')
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index('ix_gastos_placa_fecha')
        batch_op.drop_index(batch_op.f('ix_gastos_placa'))
        batch_op.drop_index('ix_gastos_categoria_fecha')

    op.drop_table('gastos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    op.drop_table('configuracion')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nombre_completo'))
        batch_op.drop_index(batch_op.f('ix_clientes_no_doc'))
        batch_op.drop_index('ix_clientes_estado_nombre')
        batch_op.drop_index(batch_op.f('ix_clientes_estado'))

    op.drop_table('clientes')
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autos_tipo'))
        batch_op.drop_index('ix_autos_estado_tipo')
        batch_op.drop_index(batch_op.f('ix_autos_estado'))

    op.drop_table('autos')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index('ix_auditoria_usuario_fecha')
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario'))
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
